version: '3.8'

services:
  service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: adsonrodrigues/django-tenants
    volumes:
      - .:/usr/local/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    networks:
      - poc-network

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1234
      - POSTGRES_DB=poc
    networks:
      - poc-network

volumes:
  postgres_data:

networks:
  poc-network:
    name: poc-network
    driver: bridge